name = "prerender-workers"
main = "src/index.ts"
compatibility_date = "2022-06-24"
routes = [
  "kodadot.preschian.xyz/rmrk/collection/*",
  "kodadot.preschian.xyz/rmrk/gallery/*",
  "kodadot.preschian.xyz/rmrk/detail/*",
  "kodadot.preschian.xyz/bsx/collection/*",
  "kodadot.preschian.xyz/bsx/gallery/*",
  "kodadot.preschian.xyz/bsx/detail/*",
  "kodadot.preschian.xyz/snek/collection/*",
  "kodadot.preschian.xyz/snek/gallery/*",
  "kodadot.preschian.xyz/snek/detail/*",
  "kodadot.preschian.xyz/glmr/collection/*",
  "kodadot.preschian.xyz/glmr/gallery/*",
  "kodadot.preschian.xyz/glmr/detail/*",
]
